# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: schema.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0cschema.proto\x12\x12my_serializer_test\" \n\rListOfStrings\x12\x0f\n\x07strings\x18\x01 \x03(\t\"\x1b\n\x0bRepeatedInt\x12\x0c\n\x04ints\x18\x01 \x03(\x05\"D\n\x12ListOfRepeatedInts\x12.\n\x05lists\x18\x01 \x03(\x0b\x32\x1f.my_serializer_test.RepeatedInt\"\xc2\x01\n\x1aStringToListOfRepeatedInts\x12L\n\x07mapping\x18\x01 \x03(\x0b\x32;.my_serializer_test.StringToListOfRepeatedInts.MappingEntry\x1aV\n\x0cMappingEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\x35\n\x05value\x18\x02 \x01(\x0b\x32&.my_serializer_test.ListOfRepeatedInts:\x02\x38\x01\"V\n\x0bListOfSTLRI\x12G\n\x0frepeated_stlris\x18\x01 \x03(\x0b\x32..my_serializer_test.StringToListOfRepeatedInts\"\xd5\x01\n\x0e\x43ustomerBasket\x12\r\n\x05items\x18\x01 \x03(\t\x12\x12\n\nquantities\x18\x02 \x03(\x05\x12\x0e\n\x06prices\x18\x03 \x03(\x02\x12>\n\x06\x63ombos\x18\x04 \x03(\x0b\x32..my_serializer_test.CustomerBasket.CombosEntry\x1aP\n\x0b\x43ombosEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\x30\n\x05value\x18\x02 \x01(\x0b\x32!.my_serializer_test.ListOfStrings:\x02\x38\x01\"\xe2\x02\n\tUserClass\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x0f\n\x07surname\x18\x02 \x01(\t\x12\x0b\n\x03\x61ge\x18\x03 \x01(\x05\x12\x17\n\x0f\x63urrent_balance\x18\x04 \x01(\x02\x12\x32\n\x06\x62\x61sket\x18\x05 \x01(\x0b\x32\".my_serializer_test.CustomerBasket\x12P\n\x12loyalty_programmes\x18\x06 \x03(\x0b\x32\x34.my_serializer_test.UserClass.LoyaltyProgrammesEntry\x12P\n\'very_complicated_list_of_dicts_of_lists\x18\x07 \x01(\x0b\x32\x1f.my_serializer_test.ListOfSTLRI\x1a\x38\n\x16LoyaltyProgrammesEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\x08:\x02\x38\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'schema_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _STRINGTOLISTOFREPEATEDINTS_MAPPINGENTRY._options = None
  _STRINGTOLISTOFREPEATEDINTS_MAPPINGENTRY._serialized_options = b'8\001'
  _CUSTOMERBASKET_COMBOSENTRY._options = None
  _CUSTOMERBASKET_COMBOSENTRY._serialized_options = b'8\001'
  _USERCLASS_LOYALTYPROGRAMMESENTRY._options = None
  _USERCLASS_LOYALTYPROGRAMMESENTRY._serialized_options = b'8\001'
  _globals['_LISTOFSTRINGS']._serialized_start=36
  _globals['_LISTOFSTRINGS']._serialized_end=68
  _globals['_REPEATEDINT']._serialized_start=70
  _globals['_REPEATEDINT']._serialized_end=97
  _globals['_LISTOFREPEATEDINTS']._serialized_start=99
  _globals['_LISTOFREPEATEDINTS']._serialized_end=167
  _globals['_STRINGTOLISTOFREPEATEDINTS']._serialized_start=170
  _globals['_STRINGTOLISTOFREPEATEDINTS']._serialized_end=364
  _globals['_STRINGTOLISTOFREPEATEDINTS_MAPPINGENTRY']._serialized_start=278
  _globals['_STRINGTOLISTOFREPEATEDINTS_MAPPINGENTRY']._serialized_end=364
  _globals['_LISTOFSTLRI']._serialized_start=366
  _globals['_LISTOFSTLRI']._serialized_end=452
  _globals['_CUSTOMERBASKET']._serialized_start=455
  _globals['_CUSTOMERBASKET']._serialized_end=668
  _globals['_CUSTOMERBASKET_COMBOSENTRY']._serialized_start=588
  _globals['_CUSTOMERBASKET_COMBOSENTRY']._serialized_end=668
  _globals['_USERCLASS']._serialized_start=671
  _globals['_USERCLASS']._serialized_end=1025
  _globals['_USERCLASS_LOYALTYPROGRAMMESENTRY']._serialized_start=969
  _globals['_USERCLASS_LOYALTYPROGRAMMESENTRY']._serialized_end=1025
# @@protoc_insertion_point(module_scope)
